### ISSUE TITLE
Databases Not Merged Between Branches

### ISSUE THREAD

**Issue by mgallagherjr** [DuckDisplay/DuckDisplayApp#22]
The duck.db file is not consistent between branches anymore. I was working on the version in DuckCardBackendDev, which had some changes made. I pulled a version from master, which overwrote my current duck.db, so I lost some changes Ben made.
Just need someone to merge these two duck.db files so that master and DuckCardBackendDev are consistent.

**Comment by BenjaminCyr** [comment]
The Database on Master now has data from both databases. See commit c8483d6389de6296287148d514a5a6ca517a0ee0
