### ISSUE TITLE
Feature Request: Audio Spectrogram

### ISSUE THREAD

**Issue by mgallagherjr** [DuckDisplay/DuckDisplayApp#24]
So this hasn't been discussed since the start of the semester, but, for the duck cards, do we want some kind of signal processing/audio spectrogram on the duck cards?
To close issue: just need a decision and how to proceed.

**Comment by asm0027** [comment]
I say no. There are still a lot of pieces that have to be finished and tested and we only have 2 weeks left in the semester.

**Comment by mgallagherjr** [comment]
Feature will *not* be integrated due to time constraints. Close #24
