### ISSUE TITLE
UI Navigation Bug: Navigation Controller Main Menu "Back" Button

### ISSUE THREAD

**Issue by mgallagherjr** [DuckDisplay/DuckDisplayApp#27]
Issues with navigation controller back button:
- Upon re-entering main menu, navigation stack should be "cleared", e.g., a "Back" button should *not* appear on the navigation bar
-- Example Sequence: Main Menu -> Play Duck Trivia Game -> Play! -> To Main Menu -> Duck Species -> Back
-- This sequence, or really anywhere there's a direct "To Main Menu" option adds the main menu onto the navigation stack, making the "Back" button appear on the main menu screen

**Comment by asm0027** [comment]
Your right Mark I have played with this bug a little bit. Should be a easy fix.
