### ISSUE TITLE
Leaderboard Not Functioning Correctly

### ISSUE THREAD

**Issue by ampruitt** [DuckDisplay/DuckDisplayApp#39]
Leaderboard is still hardcoded.
New user high score is not being added.

**Comment by mgallagherjr** [comment]
"Score" variable should be cleared after user submits name to the leaderboard list.
At the moment: can reopen leaderboard and have same score without playing trivia game again.

**Comment by asm0027** [comment]
Trivia game times out after like 10 seconds.

**Comment by mgallagherjr** [comment]
10 second timeout is no longer an issue.
Only issue remaining: Update place numbers on the Leaderboard.
