### ISSUE TITLE
Trivia Game UI

### ISSUE THREAD

**Issue by asm0027** [DuckDisplay/DuckDisplayApp#8]

**Comment by jpc0026** [comment]
The trivia screen has been pushed to the main branch.

**Comment by jpc0026** [comment]
Updated and pushed updated trivia screen with new buttons.

**Comment by asm0027** [comment]
JP I believe we will also need a second UI for the questions with Images.

**Comment by jpc0026** [comment]
Uploaded a Trivia Game UI Screen 1 that should have a background image. I am encountering an error "Linker Command Failed with Exit Code 1". Can anyone please research this.

**Comment by jpc0026** [comment]
Have completed setting a background image and looked into the second screen issue. It looks like if the image is not called by a function, it will be clear. This means only one screen will need to be made. Plan to have this ticket closed by Sunday Night.

**Comment by jpc0026** [comment]
Complete trivia game start screen and trivia game screen has been pushed to master. Ticket will be closed pending review of screens from other group members.

**Comment by jpc0026** [comment]
Besides any major changes Matt may need while writing functions. This is done. Need help merging in meeting today. After merge, ticket will be closed.
